server:
  port: 10050
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: 30b89855-8cfc-4dc4-8ccc-0aa3b38e4cd8
        group: learn
    gateway:
      routes:
        - id: user
          uri: lb://learn-user
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
        - id: order
          uri: lb://learn-order
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
