spring:
  datasource:
    username: root
    password: ROOT_12root
    url: jdbc:mysql://www.fllday.cn:3306/learn?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet:
        login-username: gss
        login-password: 584521
        url-pattern: /druid/*
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 3000
        min-idle: 0
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
server:
  port: 9090
security:
  login: /login