server:
  port: 20070
spring:
  application:
    name: learn-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 30b89855-8cfc-4dc4-8ccc-0aa3b38e4cd8
        group: learn
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: 30b89855-8cfc-4dc4-8ccc-0aa3b38e4cd8
        group: learn
        file-extension: yaml
  datasource:
    username: root
    password: ROOT_12root
    url: jdbc:mysql://www.fllday.cn:3306/learn?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: 300000
  freemarker:
    request-context-attribute: request
    suffix: .ftl
    cache: false
